using System.Collections.Generic;

namespace S57
{
    public static class S57AttributeInfo
    {
        public static Dictionary<S57Att, string> S57Dict = new Dictionary<S57Att, string>()
        {
            //source: http://www.s-57.com/
            //retrieved on January 25, 2019
            {S57Att.BCNSHP, "Beacon shape"},
            {S57Att.BUISHP, "Building shape"},
            {S57Att.BOYSHP, "Buoy shape"},
            {S57Att.BURDEP, "Buried depth"},
            {S57Att.CALSGN, "Call sign"},
            {S57Att.CATAIR, "Category of airport/airfield"},
            {S57Att.CATACH, "Category of anchorage"},
            {S57Att.CATBRG, "Category of bridge"},
            {S57Att.CATBUA, "Category of built-up area"},
            {S57Att.CATCBL, "Category of cable"},
            {S57Att.CATCAN, "Category of canal"},
            {S57Att.CATCAM, "Category of cardinal mark"},
            {S57Att.CATCHP, "Category of checkpoint"},
            {S57Att.CATCOA, "Category of coastline"},
            {S57Att.CATCTR, "Category of control point"},
            {S57Att.CATCON, "Category of conveyor"},
            {S57Att.CATCOV, "Category of coverage"},
            {S57Att.CATCRN, "Category of crane"},
            {S57Att.CATDAM, "Category of dam"},
            {S57Att.CATDIS, "Category of distance mark"},
            {S57Att.CATDOC, "Category of dock"},
            {S57Att.CATDPG, "Category of dumping ground"},
            {S57Att.CATFNC, "Category of fence/wall"},
            {S57Att.CATFRY, "Category of ferry"},
            {S57Att.CATFIF, "Category of fishing facility"},
            {S57Att.CATFOG, "Category of fog signal"},
            {S57Att.CATFOR, "Category of fortified structure"},
            {S57Att.CATGAT, "Category of gate"},
            {S57Att.CATHAF, "Category of harbour facility"},
            {S57Att.CATHLK, "Category of hulk"},
            {S57Att.CATICE, "Category of ice"},
            {S57Att.CATINB, "Category of installation buoy"},
            {S57Att.CATLND, "Category of land region"},
            {S57Att.CATLMK, "Category of landmark"},
            {S57Att.CATLAM, "Category of lateral mark"},
            {S57Att.CATLIT, "Category of light"},
            {S57Att.CATMFA, "Category of marine farm/culture"},
            {S57Att.CATMPA, "Category of military practice area"},
            {S57Att.CATMOR, "Category of mooring/warping facility"},
            {S57Att.CATNAV, "Category of navigation line"},
            {S57Att.CATOBS, "Category of obstruction"},
            {S57Att.CATOFP, "Category of offshore platform"},
            {S57Att.CATOLB, "Category of oil barrier"},
            {S57Att.CATPLE, "Category of pile"},
            {S57Att.CATPIL, "Category of pilot boarding place"},
            {S57Att.CATPIP, "Category of pipeline/pipe"},
            {S57Att.CATPRA, "Category of production area"},
            {S57Att.CATPYL, "Category of pylon"},
            //{S57Att.CATQUA, "Category of quality of data"}, //use in ENC prohibited
            {S57Att.CATRAS, "Category of radar station"},
            {S57Att.CATRTB, "Category of radar transponder beacon"},
            {S57Att.CATROS, "Category of radio station"},
            {S57Att.CATTRK, "Category of recommended track"},
            {S57Att.CATRSC, "Category of rescue station"},
            {S57Att.CATREA, "Category of restricted area"},
            {S57Att.CATROD, "Category of road"},
            {S57Att.CATRUN, "Category of runway"},
            {S57Att.CATSEA, "Category of sea area"},
            {S57Att.CATSLC, "Category of shoreline construction"},
            {S57Att.CATSIT, "Category of signal station, traffic"},
            {S57Att.CATSIW, "Category of signal station, warning"},
            {S57Att.CATSIL, "Category of silo/tank"},
            {S57Att.CATSLO, "Category of slope"},
            {S57Att.CATSCF, "Category of small craft facility"},
            {S57Att.CATSPM, "Category of special purpose mark"},
            {S57Att.CATTSS, "Category of Traffic Separation Scheme"},
            {S57Att.CATVEG, "Category of vegetation"},
            {S57Att.CATWAT, "Category of water turbulence"},
            {S57Att.CATWED, "Category of weed/kelp"},
            {S57Att.CATWRK, "Category of wreck"},
            {S57Att.CATZOC, "Category of zone of confidence in data"},
            //{S57Att.$SPACE, "Character spacing"}, //use in ENC prohibited
            //{S57Att.$CHARS, "Character specification"}, //use in ENC prohibited
            {S57Att.COLOUR, "Colour"},
            {S57Att.COLPAT, "Colour pattern"},
            {S57Att.COMCHA, "Communication channel"},
            //{S57Att.$CSIZE, "Compass size"}, //use in ENC prohibited
            //{S57Att.CPDATE, "Compilation date"}, //use in ENC prohibited
            {S57Att.CSCALE, "Compilation scale"},
            {S57Att.CONDTN, "Condition"},
            {S57Att.CONRAD, "Conspicuous, radar"},
            {S57Att.CONVIS, "Conspicuous, visually"},
            {S57Att.CURVEL, "Current velocity"},
            {S57Att.DATEND, "Date end"},
            {S57Att.DATSTA, "Date start"},
            {S57Att.DRVAL1, "Depth range value 1"},
            {S57Att.DRVAL2, "Depth range value 2"},
            //{S57Att.DUNITS, "Depth units"}, //use in ENC prohibited
            {S57Att.ELEVAT, "Elevation"},
            {S57Att.ESTRNG, "Estimated range of transmission"},
            {S57Att.EXCLIT, "Exhibition condition of light"},
            {S57Att.EXPSOU, "Exposition of sounding"},
            {S57Att.FUNCTN, "Function"},
            {S57Att.HEIGHT, "Height"},
            {S57Att.HUNITS, "Height/length units"},
            {S57Att.HORACC, "Horizontal accuracy"},
            {S57Att.HORCLR, "Horizontal clearance"},
            {S57Att.HORLEN, "Horizontal length"},
            {S57Att.HORWID, "Horizontal width"},
            {S57Att.ICEFAC, "Ice factor"},
            {S57Att.INFORM, "Information"},
            {S57Att.JRSDTN, "Jurisdiction"},
            //{S57Att.$JUSTH, "Justification - horizontal"}, //use in ENC prohibited
            //{S57Att.$JUSTV, "Justification - vertical"}, //use in ENC prohibited
            {S57Att.LIFCAP, "Lifting capacity"},
            {S57Att.LITCHR, "Light characteristic"},
            {S57Att.LITVIS, "Light visibility"},
            {S57Att.MARSYS, "Marks navigational - System of"},
            {S57Att.MLTYLT, "Multiplicity of lights"},
            {S57Att.NATION, "Nationality"},
            {S57Att.NATCON, "Nature of construction"},
            {S57Att.NATSUR, "Nature of surface"},
            {S57Att.NATQUA, "Nature of surface - qualifying terms"},
            //{S57Att.NMDATE, "Notice to Mariners date"}, //use in ENC prohibited
            {S57Att.OBJNAM, "Object name"},
            {S57Att.ORIENT, "Orientation"},
            {S57Att.PEREND, "Periodic date end"},
            {S57Att.PERSTA, "Periodic date start"},
            {S57Att.PICREP, "Pictorial representation"},
            {S57Att.PILDST, "Pilot district"},
            //{S57Att.PRCTRY, "Producing country"}, //use in ENC prohibited
            {S57Att.PRODCT, "Product"},
            {S57Att.PUBREF, "Publication reference"},
            {S57Att.QUASOU, "Quality of sounding measurement"},
            {S57Att.RADWAL, "Radar wave length"},
            {S57Att.RADIUS, "Radius"},
            //{S57Att.RECDAT, "Recording date"}, //use in ENC prohibited
            //{S57Att.RECIND, "Recording indication"}, //use in ENC prohibited
            {S57Att.RYRMGV, "Reference year for magnetic variation"},
            {S57Att.RESTRN, "Restriction"},
            //{S57Att.SCAMAX, "Scale maximum"}, //use in ENC prohibited
            {S57Att.SCAMIN, "Scale minimum"},
            {S57Att.SCVAL1, "Scale value one"},
            {S57Att.SCVAL2, "Scale value two"},
            {S57Att.SECTR1, "Sector limit one"},
            {S57Att.SECTR2, "Sector limit two"},
            {S57Att.SHIPAM, "Shift parameters"},
            {S57Att.SIGFRQ, "Signal frequency"},
            {S57Att.SIGGEN, "Signal generation"},
            {S57Att.SIGGRP, "Signal group"},
            {S57Att.SIGPER, "Signal period"},
            {S57Att.SIGSEQ, "Signal sequence"},
            {S57Att.SOUACC, "Sounding accuracy"},
            {S57Att.SDISMX, "Sounding distance - maximum"},
            {S57Att.SDISMN, "Sounding distance - minimum"},
            {S57Att.SORDAT, "Source date"},
            {S57Att.SORIND, "Source indication"},
            {S57Att.STATUS, "Status"},
            {S57Att.SURATH, "Survey authority"},
            {S57Att.SUREND, "Survey date - end"},
            {S57Att.SURSTA, "Survey date - start"},
            {S57Att.SURTYP, "Survey type"},
            //{S57Att.$SCALE, "Symbol scaling factor"}, //use in ENC prohibited
            //{S57Att.$SCODE, "Symbolization code"}, //use in ENC prohibited
            {S57Att.TECSOU, "Technique of sounding measurement"},
            //{S57Att.$TXSTR, "Text string"}, //use in ENC prohibited
            {S57Att.TXTDSC, "Textual description"},
            {S57Att.TS_TSP, "Tidal stream - panel values"},
            {S57Att.TS_TSV, "Tidal stream, current - time series values"},
            {S57Att.T_ACWL, "Tide - accuracy of water level"},
            {S57Att.T_HWLW, "Tide - high and low water values"},
            {S57Att.T_MTOD, "Tide - method of tidal prediction"},
            {S57Att.T_THDF, "Tide - time and height differences"},
            {S57Att.T_TINT, "Tide, current - time interval of values"},
            {S57Att.T_TSVL, "Tide - time series values"},
            {S57Att.T_VAHC, "Tide - value of harmonic constituents"},
            {S57Att.TIMEND, "Time end"},
            {S57Att.TIMSTA, "Time start"},
            //{S57Att.$TINTS, "Tint"}, //use in ENC prohibited
            {S57Att.TOPSHP, "Topmark/daymark shape"},
            {S57Att.TRAFIC, "Traffic flow"},
            {S57Att.VALACM, "Value of annual change in magnetic variation"},
            {S57Att.VALDCO, "Value of depth contour"},
            {S57Att.VALLMA, "Value of local magnetic anomaly"},
            {S57Att.VALMAG, "Value of magnetic variation"},
            {S57Att.VALMXR, "Value of maximum range"},
            {S57Att.VALNMR, "Value of nominal range"},
            {S57Att.VALSOU, "Value of sounding"},
            {S57Att.VERACC, "Vertical accuracy"},
            {S57Att.VERCLR, "Vertical clearance"},
            {S57Att.VERCCL, "Vertical clearance, closed"},
            {S57Att.VERCOP, "Vertical clearance, open"},
            {S57Att.VERCSA, "Vertical clearance, safe"},
            {S57Att.VERDAT, "Vertical datum"},
            {S57Att.VERLEN, "Vertical length"},
            {S57Att.WATLEV, "Water level effect"},
            {S57Att.CAT_TS, "Category of Tidal Stream"},
            //{S57Att.PUNITS, "Positional accuracy units"}, //use in ENC prohibited
            {S57Att.CLSDEF, "Object class definition"},
            {S57Att.CLSNAM, "Object class name"},
            {S57Att.SYMINS, "Symbol instruction"},
            {S57Att.NINFOM, "Information in national language"},
            {S57Att.NOBJNM, "Object name in national language"},
            {S57Att.NPLDST, "Pilot district in national language"},
            //{S57Att.$NTXST, "Text string in national language"}, //use in ENC prohibited
            {S57Att.NTXTDS, "Textual description in national language"},
            {S57Att.HORDAT, "Horizontal datum"},
            {S57Att.POSACC, "Positional Accuracy"},
            {S57Att.QUAPOS, "Quality of position"},
            {S57Att.CATBUI, "Category of building, single"},
            {S57Att.CATDYK, "Category of dyke"},
            {S57Att.CATMST, "Category of mast"},
            {S57Att.CATPRI, "Category of production installation"},
            {S57Att.CATREB, "Category of religious building"},
            {S57Att.CATTOW, "Category of tower"},
            {S57Att.CATTRE, "Category of tree"},
            {S57Att.COLMAR, "Colour of navigational mark"},
            {S57Att.QUAVEM, "Quality of vertical measurement"},
            {S57Att.SUPLIT, "Supervision of light"},
            {S57Att.CATMNT, "Category of monument"},
        };                
    }
}
